/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 09/03/2018 14:17:03
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_SYSCLKFreq_VALUE                     4000000
#define MX_HCLKFreq_Value                       4000000
#define MX_FCLKCortexFreq_Value                 4000000
#define MX_CortexFreq_Value                     4000000
#define MX_AHBFreq_Value                        4000000
#define MX_APB1Freq_Value                       4000000
#define MX_APB2Freq_Value                       4000000
#define MX_APB1TimFreq_Value                    4000000
#define MX_APB2TimFreq_Value                    4000000
#define MX_PWRFreq_Value                        4000000
#define MX_RTCFreq_Value                        32000
#define MX_USBFreq_Value                        16000000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    4000000

/*-------------------------------- I2C1       --------------------------------*/

#define MX_I2C1                                 1

/* GPIO Configuration */

/* Pin PB6 */
#define MX_I2C1_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SCL_GPIO_FM6                    __NULL
#define MX_I2C1_SCL_Pin                         PB6
#define MX_I2C1_SCL_GPIOx                       GPIOB
#define MX_I2C1_SCL_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SCL_GPIO_Pin                    GPIO_PIN_6
#define MX_I2C1_SCL_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PB7 */
#define MX_I2C1_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SDA_Pin                         PB7
#define MX_I2C1_SDA_GPIOx                       GPIOB
#define MX_I2C1_SDA_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SDA_GPIO_Pin                    GPIO_PIN_7
#define MX_I2C1_SDA_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SDA_GPIO_FM7                    __NULL
#define MX_I2C1_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- I2C2       --------------------------------*/

#define MX_I2C2                                 1

/* GPIO Configuration */

/* Pin PB11 */
#define MX_I2C2_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C2_SDA_Pin                         PB11
#define MX_I2C2_SDA_GPIOx                       GPIOB
#define MX_I2C2_SDA_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C2_SDA_GPIO_Pin                    GPIO_PIN_11
#define MX_I2C2_SDA_GPIO_AF                     GPIO_AF4_I2C2
#define MX_I2C2_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PB10 */
#define MX_I2C2_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C2_SCL_Pin                         PB10
#define MX_I2C2_SCL_GPIOx                       GPIOB
#define MX_I2C2_SCL_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C2_SCL_GPIO_Pin                    GPIO_PIN_10
#define MX_I2C2_SCL_GPIO_AF                     GPIO_AF4_I2C2
#define MX_I2C2_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 (JTMS-SWDIO) */
#define MX_SYS_JTMS-SWDIO_Pin                   PA13_(JTMS_SWDIO)

/* Pin PA14 (JTCK-SWCLK) */
#define MX_SYS_JTCK-SWCLK_Pin                   PA14_(JTCK_SWCLK)

/*-------------------------------- USART3     --------------------------------*/

#define MX_USART3                               1

#define MX_USART3_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PC4 */
#define MX_USART3_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART3_TX_Pin                        PC4
#define MX_USART3_TX_GPIOx                      GPIOC
#define MX_USART3_TX_GPIO_PuPd                  GPIO_PULLUP
#define MX_USART3_TX_GPIO_Pin                   GPIO_PIN_4
#define MX_USART3_TX_GPIO_AF                    GPIO_AF7_USART3
#define MX_USART3_TX_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PC5 */
#define MX_USART3_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART3_RX_Pin                        PC5
#define MX_USART3_RX_GPIOx                      GPIOC
#define MX_USART3_RX_GPIO_PuPd                  GPIO_PULLUP
#define MX_USART3_RX_GPIO_Pin                   GPIO_PIN_5
#define MX_USART3_RX_GPIO_AF                    GPIO_AF7_USART3
#define MX_USART3_RX_GPIO_Mode                  GPIO_MODE_AF_PP

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PB15 */
#define MX_PB15_Pin                             PB15
#define MX_PB15_GPIOx                           GPIOB
#define MX_PB15_GPIO_PuPd                       GPIO_NOPULL
#define MX_PB15_GPIO_Pin                        GPIO_PIN_15
#define MX_PB15_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PC15-OSC32_OUT (PC15) */
#define MX_PC15_OSC32_OUT_(PC15)_GPIO_Speed     GPIO_SPEED_FREQ_LOW
#define MX_PC15_OSC32_OUT_(PC15)_Pin            PC15_OSC32_OUT_(PC15)
#define MX_PC15_OSC32_OUT_(PC15)_GPIOx          GPIOC
#define MX_PC15_OSC32_OUT_(PC15)_PinState       GPIO_PIN_RESET
#define MX_PC15_OSC32_OUT_(PC15)_GPIO_PuPd      GPIO_NOPULL
#define MX_PC15_OSC32_OUT_(PC15)_GPIO_Pin       GPIO_PIN_15
#define MX_PC15_OSC32_OUT_(PC15)_GPIO_ModeDefaultOutputPP GPIO_MODE_OUTPUT_PP

/* Pin PB8 */
#define MX_PB8_Pin                              PB8
#define MX_PB8_GPIOx                            GPIOB
#define MX_PB8_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB8_GPIO_Pin                         GPIO_PIN_8
#define MX_PB8_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PA9 */
#define MX_PA9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA9_Pin                              PA9
#define MX_PA9_GPIOx                            GPIOA
#define MX_PA9_PinState                         GPIO_PIN_RESET
#define MX_PA9_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA9_GPIO_Pin                         GPIO_PIN_9
#define MX_PA9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC14-OSC32_IN (PC14) */
#define MX_PC14_OSC32_IN_(PC14)_GPIO_Speed      GPIO_SPEED_FREQ_LOW
#define MX_PC14_OSC32_IN_(PC14)_Pin             PC14_OSC32_IN_(PC14)
#define MX_PC14_OSC32_IN_(PC14)_GPIOx           GPIOC
#define MX_PC14_OSC32_IN_(PC14)_PinState        GPIO_PIN_RESET
#define MX_PC14_OSC32_IN_(PC14)_GPIO_PuPd       GPIO_NOPULL
#define MX_PC14_OSC32_IN_(PC14)_GPIO_Pin        GPIO_PIN_14
#define MX_PC14_OSC32_IN_(PC14)_GPIO_ModeDefaultOutputPP GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

